services:
  #################################################
  # OCTANE:FRANKENPHP
  #################################################
  app:
    image: ghcr.io/y-l-g/shadcn-vue-laravel-breeze-starter:main
    volumes:
      - shadcn-vue-laravel-starter_app_data:/data
      - shadcn-vue-laravel-starter_app_config:/config
    healthcheck:
      test: ["CMD", "php", "artisan", "octane:status"]
      start_period: 20s
    command: sh -c 'php artisan octane:frankenphp --host=0.0.0.0'
    environment:
      - APP_NAME=shadcn-vue-laravel-starter
    secrets:
      - shadcn-vue-laravel-starter_DB_PASSWORD
      - shadcn-vue-laravel-starter_REDIS_PASSWORD
      - shadcn-vue-laravel-starter_APP_KEY
      - shadcn-vue-laravel-starter_MAIL_HOST
      - shadcn-vue-laravel-starter_MAIL_USERNAME
      - shadcn-vue-laravel-starter_MAIL_PASSWORD
    entrypoint: start-container
    networks:
      - shadcn-vue-laravel-starter
  ##################################################
  # VOLUMES
  ##################################################
volumes:
  shadcn-vue-laravel-starter_app_data:
  shadcn-vue-laravel-starter_app_config:
secrets:
  shadcn-vue-laravel-starter_DB_PASSWORD:
    external: true
  shadcn-vue-laravel-starter_REDIS_PASSWORD:
    external: true
  shadcn-vue-laravel-starter_APP_KEY:
    external: true
  shadcn-vue-laravel-starter_MAIL_HOST:
    external: true
  shadcn-vue-laravel-starter_MAIL_USERNAME:
    external: true
  shadcn-vue-laravel-starter_MAIL_PASSWORD:
    external: true
networks:
  shadcn-vue-laravel-starter:
    external: true
